[package]
name = "video-coach-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gstreamer.workspace = true
gstreamer-app.workspace = true
gstreamer-gl.workspace = true
gstreamer-pbutils.workspace = true
gstreamer-video.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
